services:
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app
    depends_on:
      - db
    expose:
      - 9000
    entrypoint: ["/usr/local/bin/init.sh"]

  db:
    container_name: db
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - "${DB_HOST_PORT:-5432}:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - app

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "${DB_APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app
    entrypoint: [ "/bin/sh", "-c", "sleep 5 && nginx -g 'daemon off;'" ]

volumes:
  db:
    driver: local


networks:
  app:
    driver: bridge
